-- Creating a new database
CREATE DATABASE db_ecommerce;

-- Using the new database.
USE db_ecommerce;

-- Creating customers table
CREATE TABLE customers (
	customer_id INT AUTO_INCREMENT PRIMARY KEY,
   first_name VARCHAR(50) NOT NULL,
   last_name VARCHAR(50) NOT NULL,
   email VARCHAR(50) NOT NULL,
   phone VARCHAR(50) NULL
);

-- Creating producsts table
CREATE TABLE products (
	product_id INT AUTO_INCREMENT PRIMARY KEY,
	product_name VARCHAR(60) NOT NULL,
	price DECIMAL(10,2) NOT NULL,
	stock_quantity INT NOT NULL DEFAULT 0
);

-- Creating orders table
CREATE TABLE orders(
	order_id INT AUTO_INCREMENT PRIMARY KEY,
	customer_id INT NOT NULL,
	order_date DATETIME NOT NULL,
	
	FOREIGN KEY (customer_id) REFERENCES customers(customer_id)
);

-- Creating orderItems table
CREATE TABLE orderItems(
	order_item_id INT AUTO_INCREMENT PRIMARY KEY,
	order_id INT NOT NULL,
	product_id INT NOT NULL,
	quantity INT NOT NULL,
	subtotal DECIMAL(10,2) NOT NULL,
	
	FOREIGN KEY (order_id) REFERENCES orders(order_id) ON DELETE CASCADE,
	FOREIGN KEY (product_id) REFERENCES products(product_id)
);


-- CRUD Operations

-- Inserting new product
INSERT INTO products(product_name, price, stock_quantity) VALUES('Laptop', 1000.00, 50);

-- Updating product stock
UPDATE products SET stock_quantity = 75 WHERE product_id = 3;

-- Deleting order
DELETE FROM orders WHERE order_id = 10;

-- Getting customer by order id = 5
SELECT c.first_name, c.last_name FROM orders AS o JOIN customers AS c ON o.customer_id = c.customer_id WHERE o.order_id = 5;

-- Calculating total revenue generated by each product 
SELECT oi.order_id AS 'ORDER ID', p.product_name AS 'PRODUCT', SUM(oi.subtotal) AS 'TOTAL REVENUE' FROM products AS p JOIN orderItems AS oi ON p.product_id = oi.product_id GROUP BY oi.order_id, p.product_id;


-- Stored Procedure

DELIMITER //

CREATE PROCEDURE GetTotalRevenueByCustomer(IN customerID INT)
BEGIN
	SELECT
		CONCAT(c.first_name, ' ', c.last_name) AS 'CUSTOMER',
		SUM(oi.subtotal) AS 'TOTAL REVENUE'
	FROM 
		customers AS c 
	JOIN 
		orders AS o ON c.customer_id = o.customer_id
	JOIN 
		orderItems AS oi ON oi.order_id = o.order_id
	WHERE
		c.customer_id = customerID
	GROUP BY
		c.customer_id;
END //

DELIMITER ;